image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

before_script:
  - dotnet --version

# Build
build_project:
  stage: build
  tags: [windows]
  script:
    - dotnet build Robots.sln

# Test
test_project:
  stage: test
  tags: [windows]
  script:
    - dotnet test TestRobots
